# Generated by Django 5.0.6 on 2024-07-07 18:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('price_per_minute', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'verbose_name': 'Велосипед',
                'verbose_name_plural': 'Велосипеды',
                'indexes': [models.Index(fields=['available'], name='bicycles_bi_availab_fa28bb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('bicycle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bicycles', to='bicycles.bicycle')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Аренда велосипеда',
                'verbose_name_plural': 'Аренды велосипедов',
                'indexes': [models.Index(fields=['-start_time'], name='bicycles_re_start_t_870c32_idx')],
            },
        ),
    ]
